### ISSUE TITLE
Issues running pytest after cloning repo

### ISSUE THREAD

**Issue by ltrainstg** [DavidVujic/python-polylith-example-hatch#1]
# Problem 
I cloned the repo and ran through the list of commands and 'hatch run pytest' keeps returning essentially the same error for each test. 
"No module named 'example' ". 

I am using VScode on a windows system so that might be the problem. 

## Example Error 

```
_________________________________________ ERROR collecting test/bases/example/consumer/test_core.py __________________________________________ 
ImportError while importing test module '...\python-polylith-example-hatch\test\bases\example\consumer\test_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:90: in import_module 
    return _bootstrap._gcd_import(name[level:], package, level)
test\bases\example\consumer\test_core.py:1: in <module>
    from example.consumer import core
E   ModuleNotFoundError: No module named 'example'
```

## Request

I've watched most of the videos and read the docs that are available, but I can't get this to work. 
Would it be possible to get more info on initial set-up of whatever IDE you are using? 

----
** Thanks for implementing polylith in python!**

**Comment by DavidVujic** [comment]
Thank you for reporting this! I can have a look at it during tomorrow (I'm in CET time zone). I'm not on a windows system myself, but have a VM on Azure that I use for experimentation occasionally 😄 

Do you run the failing command from inside VS Code or in a shell like Powershell?

**Comment by DavidVujic** [comment]
@ltrainstg I have tried it out on Windows and both Powershell and the VS Code terminal can resolve the packages (see screenshot/animation below).

I cloned the repo and ran `hatch env create`. In addition to that - probably because I haven't used the Windows machine with Python before - I had to set the proper access to the `.venv` folder in Powershell with `Set-ExecutionPolicy` to make VS Code able to activate the virtual environment.

Please let me know if you have solved it or run into any issues!

![hatch-polylith-windows](https://github.com/DavidVujic/python-polylith-example-hatch/assets/301286/f7104455-7422-4494-9e44-39322caa5df5)

**Comment by ltrainstg** [comment]
# Issue Resolved
Thanks I was able to get it to work. 

Reiterating steps one last time. 
1. git clone ....
2. hatch env create.
3. hatch run pytest works!

To get the development part working in the screen capture I had to 
1. activate the .venv: `.venv/Scripts/activate`
2. install mypy : `pip install mypy`

This might have worked for me since I messed with the mypy settings earlier. 

## Mypy Settings posted here 

![image](https://github.com/DavidVujic/python-polylith-example-hatch/assets/16125810/88557e77-6543-49ef-9f9b-965e4927c0bb)
![image](https://github.com/DavidVujic/python-polylith-example-hatch/assets/16125810/05d4f9a1-1cde-492d-a4a0-f11d5bdd2722)


## Set-ExecutionPolicy questions
I may have already done this awhile ago, but I didn't need to make any changes. Can you post a link to how to do this or port what your execution policy is fot anyone else with this issue? 

I got mine by running `Get-ExecutionPolicy -list`

*Current ExecutionPolicy*
```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine       Undefined

```
Set-ExecutionPolicy to make VS Code able to activate the virtual environment.

## Maybe relevant links: 
1. How to pass args to PowerShell using VSCode settings. 
 https://stackoverflow.com/questions/61182855/vscode-overrides-powershell-executionpolicy

2. How to directly change PowerShell permissions
https://stackoverflow.com/questions/47023796/visual-studio-code-unsigned-powershell-scripts

___
**Thanks again for the help and quick response.**

**Comment by DavidVujic** [comment]
This is great news @ltrainstg!

About the Set-ExecutionPolicy: I probably did it the wrong way and set it to unrestricted, but mainly because I wanted to quickly test it in a temporary VM.
